#IMPORTING THE LIBRARIES

In [13]:
import pandas as pd
import numpy as np
import tensorflow as tf

#IMPORTING THE DATASET

In [14]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
X = dataset.iloc[:, :-1].values #columns 0,1,2 index does not provide any impact for the model. so we start from 3rd column and exclude the last column
y = dataset.iloc[:, -1].values

In [15]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [16]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


#Splitting dataset into train and test cell

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

#Part 2-Build the ANN

Initializing the ANN

In [18]:
ann=tf.keras.models.Sequential()

Adding the input layer and the first hidden layer

In [19]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) #6 neurons in the hidden layer

Adding the second hidden layer

In [20]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

Adding the ouput layer

In [21]:
ann.add(tf.keras.layers.Dense(units=1)) #no activation function for regression

#Training the ANN

Compiling the ANN

In [22]:
ann.compile(optimizer='adam',loss='mean_squared_error',metrics=['accuracy'])
#optimizer updates the weight through stochastic gradient descent
#loss to compute difference between predictions and real
#metrics for accuracy
#loss=mean squared error for regression

Training the ANN on the training set

In [23]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)
#batch size refers to number of predictions vs  the real results
#epochs refer to number of times the neural network is trained

Epoch 1/100
240/240 [==============================] - 1s 1ms/step - loss: 76140.5703 - accuracy: 0.0000e+00
Epoch 2/100
240/240 [==============================] - 0s 1ms/step - loss: 136.7055 - accuracy: 0.0000e+00
Epoch 3/100
240/240 [==============================] - 0s 1ms/step - loss: 130.8613 - accuracy: 0.0000e+00
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 126.2600 - accuracy: 0.0000e+00
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 120.6682 - accuracy: 0.0000e+00
Epoch 6/100
240/240 [==============================] - 0s 1ms/step - loss: 114.5647 - accuracy: 0.0000e+00
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 108.0589 - accuracy: 0.0000e+00
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 101.0742 - accuracy: 0.0000e+00
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 94.1189 - accuracy: 0.0000e+00
Epoch 10/100
240/240 [==============

#Making the predictions and evaluating the model

#Predicting the Test set results

In [26]:
y_pred = ann.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

60/60 [==============================] - 0s 3ms/step
[[430.94580078 431.23      ]
 [462.04815674 460.01      ]
 [465.56576538 461.14      ]
 ...
 [472.78607178 473.26      ]
 [439.58282471 438.        ]
 [458.8024292  463.28      ]]


#Making the confusion matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)